apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://db.internal.svc:5432/bankingdb
  DB_USER: banking_user
  DB_PASSWORD: change_this_password
